[package]
name = "commboard"
version = "0.1.0"
authors = ["Andrew Abbott <mirrexagon@mirrexagon.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

rocket = "0.4.5"
