[package]
name = "commboard"
version = "0.1.0"
authors = ["Andrew Abbott <mirrexagon@mirrexagon.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
thiserror = "1.0.26"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
clap = "2.33.3"

[build-dependencies]
walkdir = "2.3.2"
