[package]
name = "commboard"
version = "0.1.0"
authors = ["Andrew Abbott <andrew@mirx.dev>"]
edition = "2018"

[dependencies]
thiserror = "1.0.26"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
clap = "2.33.3"
