[package]
name = "commboard"
version = "0.1.0"
authors = ["Andrew Abbott <mirrexagon@mirrexagon.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.21"

serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"

rocket = "0.4.5"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json"]

[build-dependencies]
walkdir = "2.3.1"
